Table Politicians {
    id int [pk, increment]
    firstName varchar
    lastName varchar
    phone varchar
    platform varchar
    donationId int [ref: > Donations.id]
}

Table Pacs {
    id int [pk, increment]
    name varchar
    amount int
    date varchar
    corporationId int [ref: > Corporations.id]
}

Table Corporations {
    id int [pk, increment]
    name varchar
    interestId int [ref: > Interests.id]
}

Table Bills {
    id int [pk, increment]
    name varchar
    interestId int [ref: - Interests.id]
    politicianId int [ref: > Politicians.id]
}

Table Donations {
    id int [pk, increment]
    pacId int [ref: > Pacs.id]
    politicianId int [ref: > Politicians.id]
}

Table Interests {
    id int [pk, increment]
    name int
}